version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://root:password@mysql/db"
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
